#!/usr/bin/with-contenv sh

cat <<"EOF"
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         _               _
    __ _| |__   ___  ___| |_
   / _` | '_ \ / _ \/ __| __/
  | (_| | | | | (_) \__ \ |_
   \__, |_|_|_|\___/|___/\__|
   |___/      /   _ \
          (¯\| o (@) |/¯)
           \_  .___.  _/
            /   !_!   \
           /_.--._.--._\

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
EOF

# only chown the /data directory if it is not owned by abc:abc
CHOWN_DIR=/data
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:users" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi

# only chown the /tmpdata directory if it is not owned by abc:abc
CHOWN_DIR=/tmpdata
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:users" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi

# only chown the /media directory if it is not owned by abc:abc
CHOWN_DIR=/media
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:users" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi

# only chown the /config directory if it is not owned by abc:abc
CHOWN_DIR=/config
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:users" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi

# only chown the /root directory if it is not owned by abc:abc
CHOWN_DIR=/root
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`
if [[ $DIR_OWNER != "abc:users" ]]
then
    echo "chowning $CHOWN_DIR please be patient"
    chown -R abc:abc $CHOWN_DIR
fi
